.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PACKPACK" "1" "October 2016" "" ""
.
.SH "NAME"
\fBpackpack\fR \- simple tool to build RPM and Debian packages from git
.
.SH "SYNOPSIS"
.
.nf

git_repo$ OS=ubuntu DIST=xenial packpack [TARGET]
git_repo$ OS=debian DIST=sid packpack [TARGET]
git_repo$ OS=fedora DIST=24 packpack [TARGET]
git_repo$ OS=centos DIST=7 packpack [TARGET]
.
.fi
.
.SH "DESCRIPTION"
\fBPackPack\fR is a simple tool to build RPM and Debian packages from a git repository:
.
.IP "\(bu" 4
Fast reproducible builds using Docker containers
.
.IP "\(bu" 4
Semantic versioning based on annotated git tags
.
.IP "\(bu" 4
Support for all major Linux distributions as targets
.
.IP "" 0
.
.SH "TARGETS"
.
.IP "\(bu" 4
tarball \- pack a source tarball\.
.
.IP "\(bu" 4
prepare \- prepare a build directory\.
.
.IP "\(bu" 4
package \- build packages (default)\.
.
.IP "\(bu" 4
clean \- remove all created files\.
.
.IP "" 0
.
.SH "ENVIRONMENT"
\fBPackPack\fR settings can be overriden using environment variables:
.
.IP "\(bu" 4
\fBOS\fR \- target operating system name, e\.g\. \fBfedora\fR or \fBubuntu\fR
.
.IP "\(bu" 4
\fBDIST\fR \- target distribution name, e\.g \fB24\fR or \fBxenial\fR
.
.IP "\(bu" 4
\fBBUILDDIR\fR \- a directory used to store intermediate files and resulted packages (default is \fB\./build\fR)\.
.
.IP "\(bu" 4
\fBPRODUCT\fR \- the name of software product, used for source tarball and source package, e\.g\. \fBtarantool\fR
.
.IP "\(bu" 4
\fBVERSION\fR \- semantic version of the software, e\.g\. 2\.4\.35 (default is extracted for \fBgit describe\fR)\.
.
.IP "\(bu" 4
\fBRELEASE\fR \- the number of times this version of the software has been packaged (default is 1)\.
.
.IP "\(bu" 4
\fBTARBALL_COMPRESSOR\fR \- a compression algorithm to use, e\.g\. gz, bz2, xz (default is xz)\.
.
.IP "\(bu" 4
\fBCHANGELOG_NAME\fR, \fBCHANGELOG_EMAIL\fR, \fBCHANGELOG_TEXT\fR \- information used to bump version in changelog files\.
.
.IP "\(bu" 4
\fBDOCKER_REPO\fR \- a Docker repository to use (default is \fBpackpack/packpack\fR)\.
.
.IP "" 0
.
.P
See the full list of available options and detailed configuration guide in </usr/share/packpack/config\.mk> configuration file\.
.
.SH "EXIT STATUS"
\fBpackpack\fR exits with a status of zero status on success\.
.
.SH "BUGS"
See \fIhttps://github\.com/packpack/packpack/issues\fR
.
.SH "DOCUMENTATION"
See \fIhttps://github\.com/packpack/packpack\fR
.
.SH "SEE ALSO"
mock(1), pbuilder(1), git\-buildpackage(1), rpm(1)
